setup weather ui
Andria35/EcoTracker pull request #1
Opened 2023-11-29 22:02 UTC by sofoetno

2023-11-30 09:21 UTC, Andria35 requested changes
ყველაფერი ძაან კარგია, minor რაღაცეები მიგიწერე 😄

2023-11-30 09:21 UTC, Andria35 commented on EcoTracker/Scenes/Custom/CustomTextField.swift
> +        return bounds.inset(by: padding)
ერთ ხაზიან ფუნქციაში return ებზე ნანა ჭედავს თორე მე მომწონს 🙄

2023-11-30 09:21 UTC, Andria35 commented on EcoTracker/Scenes/Custom/CustomTextField.swift
> +        return bounds.inset(by: padding)
აქაც

2023-11-30 09:21 UTC, Andria35 commented on EcoTracker/Scenes/Custom/CustomTextField.swift
> +        return bounds.inset(by: padding)
აქაც

2023-11-30 09:21 UTC, Andria35 commented on EcoTracker/Scenes/Weather/WeatherViewController.swift
> +    func setupGetInformationStackView() {
მეთოდები კონტროლერის private preferrable

2023-11-30 09:21 UTC, Andria35 commented on EcoTracker/Scenes/Weather/WeatherViewController.swift
> +    func setupCoordinatesStackView() {
აქაც private და ქვემოთ ყველგან სადაც მხოლოდ კონტროლერის მეთოდია

2023-11-30 09:21 UTC, Andria35 commented on EcoTracker/Scenes/Custom/CustomTextField.swift
> +class CustomTextField: UITextField {
final class

2023-11-30 09:51 UTC, sofoetno commented on EcoTracker/Scenes/Custom/CustomTextField.swift
> +        return bounds.inset(by: padding)
ნანა გვინახავს ამ კომენტარს :DD

2023-11-30 10:03 UTC, sofoetno commented
@Andria35  ანდრია, შევიტანე ცვლილებები. მადლობა რივიუებისთვის.

2023-11-30 10:24 UTC, Andria35 approved these changes

2023-12-01 12:10 UTC, Anikardava97 approved these changes
მშვენიერია ყველაფერი, 3 კომენტარი მიგიწერე ზომებთან დაკავშირებით და გადახედე <3

2023-12-01 12:10 UTC, Anikardava97 commented on EcoTracker/Scenes/Custom/CustomTextField.swift
> +    private let padding = UIEdgeInsets(top: 17, left: 16, bottom: 17, right: 16)
top, bottom-იც 16 გააკეთე რა, არ გვინდა კენტები:დ

2023-12-01 12:10 UTC, Anikardava97 commented on EcoTracker/Scenes/Weather/WeatherViewController.swift
> +    private let weahtherTypeLabel = UILabel()
weather

2023-12-01 12:10 UTC, Anikardava97 commented on EcoTracker/Scenes/Weather/WeatherViewController.swift
> +        coordinatesStackView.spacing = 11
12

2023-12-01 12:46 UTC, sofoetno commented
@Anikardava97 ანი, შევიტანე ცვლილებები. მადლობა <3

2023-12-01 15:07 UTC, giorgixuxia approved these changes

2023-12-01 15:19 UTC, nikagacho approved these changes
რეთარნების თემა შემდეგ პრში გასწორებულია, დანარჩენი სუპერ

2023-12-01 16:45 UTC, merged