Weather view model
Andria35/EcoTracker pull request #2
Opened 2023-11-30 08:07 UTC by sofoetno

2023-11-30 09:35 UTC, Andria35 requested changes
ყველაფერი სუპერ, 1 minor detail.

2023-11-30 09:35 UTC, Andria35 commented on EcoTracker/Scenes/Weather/WeatherViewController.swift
> +        DispatchQueue.main.async {
როცა async/await ით ვმუშაობთ Main thread ზე გადასვლა სასურველია MainActor.run{} - ით მოხდეს და DispatchQueue არ გამოვიყენოთ

2023-11-30 10:17 UTC, sofoetno commented on EcoTracker/Scenes/Weather/WeatherViewController.swift
> +        DispatchQueue.main.async {
done

2023-11-30 10:25 UTC, Andria35 approved these changes

2023-12-01 12:32 UTC, Anikardava97 approved these changes
ერთი კომენტარი მიგიწერე არქიტექტურაზე, კონტროლერიდან შეგიძლია ლოგიკა მოდელში წაიღო, დანარჩენი სუპერ <3

2023-12-01 12:32 UTC, Anikardava97 commented on EcoTracker/Scenes/Weather/WeatherViewController.swift
> +            if cityName == "" && (long == "" || lat == "") {
ეს ლოგიკა ვიუმოდელში ხო არ სჯობს?

2023-12-01 13:01 UTC, sofoetno commented on EcoTracker/Scenes/Weather/WeatherViewController.swift
> +            if cityName == "" && (long == "" || lat == "") {
@Anikardava97  Done

2023-12-01 15:07 UTC, giorgixuxia approved these changes

2023-12-01 15:18 UTC, nikagacho approved these changes

2023-12-01 16:46 UTC, merged